### ISSUE TITLE
👑 [需求]搞清楚启动时为什么会出现5个autoMate.exe和2个autoMateServer.exe进程

### ISSUE THREAD

**Issue by yuruotong1** [yuruotong1/autoMate#25]
![f86ebb6f25594b7ed639255587300c2](https://github.com/yuruotong1/autoMate/assets/31992251/c04ab471-4fb4-49f6-a47c-9f88385e69b1)

**Comment by yuruotong1** [comment]
> ![automate-screenshot](https://private-user-images.githubusercontent.com/30225423/347862398-e4d124fa-4584-4661-91a2-73e198bf973c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3OTY0MzMsIm5iZiI6MTcyMDc5NjEzMywicGF0aCI6Ii8zMDIyNTQyMy8zNDc4NjIzOTgtZTRkMTI0ZmEtNDU4NC00NjYxLTkxYTItNzNlMTk4YmY5NzNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDE0NTUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2YTBiMzgwYzEwZGVjYjFkMTFjNDkxNWFiYmMwODM0MDk2ODA5MGE5MGUwY2QwNDdmNTBkN2RlMTM3MDE0YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lo0NM51a_q8oPpVjnRxplhtpeqyde4dbc_4pqbnlUkk) 这边看下来应该是通过Electron框架引入的,类似Chromium,有`gpu-process`、`utility`、`renderer`这些进程. 可以通过[process-explorer](https://learn.microsoft.com/en-us/sysinternals/downloads/process-explorer)这个工具来看到进程的具体信息. 希望对这个问题能有些帮助...

目前来看应该不影响使用，感谢提供线索！这是不是electron的正常机制呀

**Comment by xujiajiadexiaokeai** [comment]
> > ![automate-screenshot](https://private-user-images.githubusercontent.com/30225423/347862398-e4d124fa-4584-4661-91a2-73e198bf973c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3OTY0MzMsIm5iZiI6MTcyMDc5NjEzMywicGF0aCI6Ii8zMDIyNTQyMy8zNDc4NjIzOTgtZTRkMTI0ZmEtNDU4NC00NjYxLTkxYTItNzNlMTk4YmY5NzNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDE0NTUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2YTBiMzgwYzEwZGVjYjFkMTFjNDkxNWFiYmMwODM0MDk2ODA5MGE5MGUwY2QwNDdmNTBkN2RlMTM3MDE0YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lo0NM51a_q8oPpVjnRxplhtpeqyde4dbc_4pqbnlUkk) 这边看下来应该是通过Electron框架引入的,类似Chromium,有`gpu-process`、`utility`、`renderer`这些进程. 可以通过[process-explorer](https://learn.microsoft.com/en-us/sysinternals/downloads/process-explorer)这个工具来看到进程的具体信息. 希望对这个问题能有些帮助...
> 
> 目前来看应该不影响使用，感谢提供线索！这是不是electron的正常机制呀

是的，是Electron项目正常的进程架构模型
