### ISSUE TITLE
👑 [需求]与智子对话，能够对已有代码进行修改，而不是重新生成代码

### ISSUE THREAD

**Issue by yuruotong1** [yuruotong1/autoMate#5]

**Comment by zcyztf** [comment]
请问项目里有考虑过引入第三方的agent开发框架吗？比如langchain这种？我简单看了下项目，现在基础的prompt管理和agent管理都没有，而且考虑到你这个需求还需要基于已有的代码进行修改，肯定也要涉及到历史管理，你们下一步准备怎么做呀
